### ISSUE TITLE
Flush plugin/theme translation cache

### ISSUE THREAD

**Issue by grappler** [wearerequired/traduttore-registry#13]
The API results from the Tradotorre is cached for 12 hours. This means that any new languages that are added with the cache period are not available to be updated.

https://github.com/wearerequired/traduttore-registry/blob/master/inc/namespace.php#L103-L107

- [x] We need a way to flush the cache.
- [x] The cache should **not** save empty results.

**Comment by swissspidy** [comment]
> We need a way to flush the cache.

If you want to manually flush the cache you can use `wp transient delete …`

As for automatically flushing the cache you would need to define a trigger that forces deletion of the transient. I doubt that this is feasible.

> The cache should not save empty results.

Wanna open a PR for that? :-)

Alternatively, what about a super low cache duration for empty results, e.g. 5 minutes?

**Comment by grappler** [comment]
> Wanna open a PR for that?

Can do.

> If you want to manually flush the cache you can use `wp transient delete …`

This is a lot of work for multiple plugins.

> Alternatively, what about a super low cache duration for empty results, e.g. 5 minutes?

I don't think that is good as `\Required\Traduttore_Registry\add_project()` is called on every page load as it loaded in `after_setup_theme`.

> As for automatically flushing the cache you would need to define a trigger that forces deletion of the transient. I doubt that this is feasible.

WordPress uses [`wp_clean_update_cache()`](https://developer.wordpress.org/reference/functions/wp_clean_update_cache/) which we could use.

**Comment by grappler** [comment]
> The cache should not save empty results.

Actually I think it is ok that the cache is saving empty results. The alternative is not better.

It maybe good to discuss this further in a call.

**Comment by ocean90** [comment]
Good hint with `wp_clean_update_cache()`.  We can probably hook into the `delete_site_transient()` calls for `update_plugins` and `update_themes` and delete the specific caches too. Maybe it's worth exploring to only have one transient for all plugins/themes in `get_translations()`. (Note that transient keys need to be 172 characters or fewer in length which can become an issue with longer plugin/theme slugs.

Related: https://github.com/wp-cli/cache-command/issues/41

**Comment by swissspidy** [comment]
That‘s what I suggested in https://github.com/wearerequired/traduttore-registry/issues/13#issuecomment-437012263. 1 hour seems fair.

**Comment by ocean90** [comment]
Currently, when the transients are expired, the HTTP requests can also happen on the front end due to the updates item in the toolbar. We should try to avoid that IMO.

**Comment by grappler** [comment]
> We should try to avoid that IMO.

Would `is_admin()` work to solve this?
