### ISSUE TITLE
Add WP-CLI Commands

### ISSUE THREAD

**Issue by grappler** [wearerequired/traduttore-registry#14]
Today as I was debugging why the translations were not downloading it would have been useful to have two WP-CLI commands.

- [x] One to check the results of `get_translations()` for the themes and plugins.
- [x] Secondly one to clear the cached API results. Related to #13 

I am not sure if the WP-CLI commands should be added to this package or separately so to make sure that there is no conflict.

**Comment by swissspidy** [comment]
> One to check the results of `get_translations()` for the themes and plugins.

`wp eval` or `wp language`?

> Secondly one to clear the cached API results

`wp transient delete`, `wp option delete`.

> I am not sure if the WP-CLI commands should be added to this package or separately so to make sure that there is no conflict.

IMO this library should stay what it is: a library.

For dedicated debugging measures I would create a separate WP-CLI command or other project if really needed.

**Comment by grappler** [comment]
> `wp eval` or `wp language`?

The problem with `eval` is that it gets quite long. 
```
wp eval "var_dump(\Required\Traduttore_Registry\get_translations('theme','gorilla','https://translate.required.com/api/translations/schtifti/gorilla/'));"
```

I don't think that `wp language theme list gorilla` is very helpful as it does not really tell you where the problem could be.

> `wp transient delete`, `wp option delete`

The transient command could work but I forgot I needed to use network flag as the transient is being saved as a site transient. It is also a bit of work figuring out what the transient key is.
`wp transient delete theme_translations_gorilla --network`

**Comment by ocean90** [comment]
I'm assuming that once #13 is solved properly non of the commands is required anymore as it should just work.

**Comment by ocean90** [comment]
After #20  the commands would be `wp transient get traduttore-registry-plugins --network` or `wp transient get traduttore-registry-themes --network`.

**Comment by ocean90** [comment]
Let's close this now that the transients have been simplified.
