### ISSUE TITLE
Only inject enabled languages

### ISSUE THREAD

**Issue by danieliser** [wearerequired/traduttore-registry#28]
As we discussed on slack it appears that when injecting translations via the `site_transient_update_plugins` filter only those that you want to be installed via the updater should be returned.

Currently it is returning all available languages returned from GlotPress.

It should only be returning languages that are currently already enabled for this WP install.

The solution was simple enough.

In this loop: https://github.com/wearerequired/traduttore-registry/blob/master/inc/namespace.php#L71-L85

You also need to check if the language is active on the site or not, skip it if not.

			$translations = get_translations( $type, $slug, $api_url );
			if ( ! isset( $translations['translations'] ) ) {
				return $value;
			}
			$installed_translations = wp_get_installed_translations( $type . 's' );

			$locales = array_values( get_available_languages() );
			$locales = apply_filters( 'plugins_update_check_locales', $locales );
			$active_locales = array_unique( $locales );

			foreach ( (array) $translations['translations'] as $translation ) {

				// This the site doesn't use this language.
				if ( ! in_array( $translation['language'], $active_locales ) ) {
					continue;
				}

				if ( isset( $installed_translations[ $slug ][ $translation['language'] ] ) && $translation['updated'] ) {
					$local  = new DateTime( $installed_translations[ $slug ][ $translation['language'] ]['PO-Revision-Date'] );
					$remote = new DateTime( $translation['updated'] );
					if ( $local >= $remote ) {
						continue;
					}
				}
				$translation['type'] = $type;
				$translation['slug'] = $slug;
				$value->translations[] = $translation;
			}

**Comment by swissspidy** [comment]
Makes sense.

@ocean90 @grappler Could you implement this? 😁

**Comment by swissspidy** [comment]
@danieliser FYI there's now a PR at #30 with your proposed solution. Wanna test it? 🙂
