### ISSUE TITLE
Fatal Error if current language file contains '(' or ')' characters in PO-Revision-Date header

### ISSUE THREAD

**Issue by nickcernis** [wearerequired/traduttore-registry#32]
If a site has an existing theme/plugin language file, and that language file contains a `PO-Revision-Date` header with a character `DateTime` cannot parse such as `(` or `)`, Traduttore Registry throws this error:

```
2020-02-27 13:28:20.640776 [NOTICE] … [STDERR] PHP Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (Tue Dec 22 2015 12:52:19 GMT+0100 (West-Europa ) at position 39 (-): Unexpected character in /home/user/domains/example.com/public_html/wp-content/themes/genesis/lib/vendor/traduttore.php:85
Stack trace:
#0 /home/user/domains/example.com/public_html/wp-content/themes/genesis/lib/vendor/traduttore.php(85): DateTime->__construct('Tue Dec 22 2015...')
#1 /home/user/domains/example.com/public_html/wp-includes/class-wp-hook.php(290): Required\Traduttore_Registry\{closure}(Object(stdClass))
#2 /home/user/domains/example.com/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(stdClass), Array)
#3 /home/user/domains/example.com/public_html/wp-includes/option.php(1800): apply_filters('site_transient_...', Object(stdClass), 'update_themes')
#4 /home/user/domains/example.com/public_html/wp-includes/update.php(665): get_site_transient('update_themes')
#5 /home/user/domains/example in /home/user/domains/example.com/public_html/wp-content/themes/genesis/lib/vendor/traduttore.php on line 85
```
## Example PO-Revision-Date headers that break Traduttore Registry
These were both reported in the wild from production sites (ends are clipped because the stack trace was generated at that point):

- `"PO-Revision-Date: Tue Dec 22 2015 12:52:19 GMT+0100 (West-Europa"`
- `"PO-Revision-Date: Tue Jan 12 2016 15:04:22 GMT+0100 (Romance "`

The issue is the opening `(` and closing `)` characters, which DateTime cannot parse: https://3v4l.org/GIE5E

## Suggested fix
One fix would be to fall back to the Unix epoch if `DateTime` cannot parse the revision date string.

This assumes it's safe to treat unparseable `PO-Revision-Date` headers as older than the version on the server, which is probably reasonable.

```diff
				if ( $translation['updated'] && isset( $installed_translations[ $slug ][ $translation['language'] ] ) ) {
-					$local  = new DateTime( $installed_translations[ $slug ][ $translation['language'] ]['PO-Revision-Date'] );
+					try {
+						$local = new DateTime( $installed_translations[ $slug ][ $translation['language'] ]['PO-Revision-Date'] );
+					} catch (Exception $e) {
+						$local = new DateTime('1970-01-01');
+					}
+
					$remote = new DateTime( $translation['updated'] );

					if ( $local >= $remote ) {
						continue;
					}
				}
					
```

**Comment by ocean90** [comment]
The suggest change looks good to me. We could probably also strip everything after a `(` before passing it to `DateTime`. Do you have any reports with some more recent dates?

**Comment by nickcernis** [comment]
Thanks, @ocean90. I'm still trying to collect data about how those files were generated, but the site owners don't know so far. (Someone else handled their site translations who they're no longer in contact with.)

2016 is the most recent header we've seen so far.
